### ISSUE TITLE
Feature Request: Disable Logs

### ISSUE THREAD

**Issue by yuyang9119** [andywiecko/BurstTriangulator#120] opened 2024-04-10 03:12 UTC
Thank you to the author of the package. I've used this package to extend the UI's Image component. However, I encountered a small issue where when I call it in `OnDrawGizmosSelected`, if there are any vertex errors, it continuously outputs logs. I only want to draw the wireframe in red to alert the user. Is it possible to provide an option to disable log output?

![屏幕截图 2024-04-10 110940](https://github.com/andywiecko/BurstTriangulator/assets/18855621/965ee04f-9c84-4e2a-964f-bd4d352c0f43)
![屏幕截图 2024-04-10 111000](https://github.com/andywiecko/BurstTriangulator/assets/18855621/5acb6b72-6a7f-4edf-abe9-9fbe60fe8203)
![屏幕截图 2024-04-10 111020](https://github.com/andywiecko/BurstTriangulator/assets/18855621/c6dd482e-f4cc-406f-9a3a-41d921e2152c)

**Comment by yuyang9119** [comment] 2024-04-10 04:03
I have a few more minor questions:

1. If subdivision is not used, can it be guaranteed that the output position list will be exactly the same as the input vertex array? If so, it would eliminate the need for caching the result in an array. I also suggest providing an option to avoid allocating an extra output list during the calculation process.

2. For small tasks, Is synchronous immediate execution possible? In my UI extensions, there is usually a small amount of data, and synchronous immediate execution might be more efficient.

3. Every time I modify vertex data, an error log appears, but the input data is correct, and the output result is also correct. I can't find the reason; can you help me take a look?

[MeshImage.zip](https://github.com/andywiecko/BurstTriangulator/files/14926854/MeshImage.zip)

**Comment by andywiecko** [comment] 2024-04-10 06:11
Hi @yuyang9119 

Thanks for the contribution!

> Is it possible to provide an option to disable log output?

Currently, `BurstTriangulator` outputs logs only when `ValidateInput = true`. If I understand correctly, you're using `Triangulator` on `OnDrawGizmosSelected`, resulting in multiple runs for the same result during gizmo drawing. You can additionally verify the triangulation status in `Output.Status` for any errors, including those from validation. You could implement a simple check to disable/enable `Validation` for future draws if the status is OK. However, caching the `Triangulator` result might be a better approach to avoid multiple runs and logs.

> 1. If refinement is not enabled, can it be guaranteed that the output position list will be exactly the same as the input vertex array? If so, it would eliminate the need for caching the result in an array. I also suggest providing an option to avoid allocating an extra output list during the calculation process.

Could you clarify what you mean by "exactly the same"? The input/output positions array should match up to a certain floating-point precision. You can always rely on your input data for 100% precision. Regarding caching/allocation, we're planning to add this feature soon. Currently, the package is undergoing significant development and many exciting features are coming :)

> 2. For small tasks, Is synchronous immediate execution possible? In my UI extensions, there is usually a small amount of data, and synchronous immediate execution might be more efficient.

Do you mean running on the main thread or synchronous compilation? The API includes `Triangulator.Run()` method, which currently calls `IJob.Schedule().Complete()`. With recent changes, it can be simplified to `Triangulator.Run() -> IJob.Run()`. I'll include this in the upcoming release!

> 3. Every time I modify vertex data, an error log appears, but the input data is correct, and the output result is also correct. I can't find the reason; can you help me take a look?

Certainly! I'll investigate this issue sometime this week and get back to you.

---

Best, 
Andrzej

**Comment by yuyang9119** [comment] 2024-04-10 08:48
I appreciate your response and glad to see that you are continuing to update this package. Here are some additional details to clarify my previous questions.

Yes, I've already cached the results in the code. However, users may continue to input incorrect data (such as dragging coordinates with the mouse), resulting in a large number of error logs being output. From a UX/UI design perspective, the best way to handle this is to retrieve error information and display it in the inspector, rather than outputting it to the console. However, this requires support for custom error handling.

> Could you clarify what you mean by "exactly the same"?

In my UI extension, there is no support for digging holes or refinement, so I guess that the output position list is exactly the same as the input vertex array—same coordinates, same quantity, and same order. In the previous comment, I provided the source code. In the code, `_vertices` represent the input, and `_positions` represent the result. If it can be confirmed that these two are identical, I can remove `_positions`.

Regarding "synchronous immediate execution," what I mean is to run directly on the calling thread without using multithreading. I recall some articles mentioning that if the amount of data to process is small, the overhead of using multithreading itself becomes non-negligible, and ultimately the time consumed may be greater than processing directly on a single thread. Whether to execute immediately on the calling thread or to use multithreading, I think there are two ways to handle it: one is to let the programmer decide, and the other is to automatically decide based on the amount of data.

> Certainly! I'll investigate this issue sometime this week and get back to you.

Thank you very much, I await your response patiently.

**Comment by andywiecko** [comment] 2024-04-13 11:15
I've checked your example, but I'm afraid I'm not quite sure what the issue is; it seems to be working as expected to me. There are some errors in the console related to bad input, but for valid input, the triangulation performs correctly. Could you please provide more details about the issue?

https://github.com/andywiecko/BurstTriangulator/assets/15237586/23ff8d44-b28a-45e2-b225-6e31590649b8

---

> For small tasks, Is synchronous immediate execution possible? In my UI extensions, there is usually a small amount of data, and synchronous immediate execution might be more efficient.

BTW, I've just merged aa55beca9d70b86de6ff8c1e0ed45559f2b1f129 on a `main` branch and `triangulator.Run()` now works on the main thread . This will certainly be included in the future release. I will also push the requested `Verbose` option, probably today or tomorrow.

**Comment by yuyang9119** [comment] 2024-04-15 04:34
> Could you please provide more details about the issue?

I just discovered that this issue is related to how Unity Prefabs work, and the error is only outputted when the Prefab synchronizes data to the instance. This problem does not belong to this package. Thank you for your assistance!

**Comment by andywiecko** [comment] 2024-04-16 17:08
You're welcome! If you have any other questions, feel free to let me know!

I've just pushed b9b6dbba5bc888342fe5e94f32106fa0b8e461bb to the main branch. This commit includes the requested feature and it will be included in the future release. To disable logging in the Console, set `Verbose` to `false`:

```csharp
triangulator.Settings.Verbose = false;
```

By the way, in your previous example, I noticed the `#if UNITY_EDITOR` directive around `ValidateInput`. Since `v2` validation is supported in builds, playmode, etc, so you can safely skip this :)

**Closed** 2024-07-04 17:48 UTC
